# Generated by Django 4.2.1 on 2023-06-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id_mensaje', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='id_mensaje')),
                ('desc_nombre', models.CharField(max_length=250, verbose_name='desc_nombre')),
                ('email', models.EmailField(max_length=50, verbose_name='desc_email')),
                ('desc_mensaje', models.TextField(max_length=500, verbose_name='desc_mensaje')),
            ],
        ),
    ]
