# Generated by Django 4.2.1 on 2023-06-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensajeContacto',
        ),
    ]
