# Generated by Django 4.2.1 on 2023-06-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacto', '0002_delete_mensajecontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_nombre', models.CharField(max_length=250, verbose_name='desc_nombre')),
                ('email', models.EmailField(max_length=50, verbose_name='desc_email')),
                ('desc_mensaje', models.TextField(max_length=500, verbose_name='desc_mensaje')),
            ],
        ),
    ]
