# Generated by Django 4.2.1 on 2023-06-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_playlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayList',
        ),
    ]
