# Generated by Django 4.2.1 on 2023-07-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0008_playlist_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='url',
        ),
    ]
