# Generated by Django 4.2.1 on 2023-07-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0009_remove_playlist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='url',
            field=models.CharField(default=None, max_length=250, verbose_name='URL'),
        ),
    ]
