# Generated by Django 4.2.1 on 2023-07-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0010_playlist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='estado',
            field=models.CharField(choices=[('d', 'No leído'), ('p', 'Leído')], default='d', max_length=1, verbose_name='Estado'),
        ),
    ]
