# Generated by Django 4.2.1 on 2023-07-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0012_alter_mensajecontacto_options_alter_playlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='estado',
            field=models.CharField(choices=[('d', 'Nuevo'), ('p', '')], default='d', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='estado',
            field=models.CharField(choices=[('d', 'Nuevo'), ('p', '')], default='d', max_length=1, verbose_name='Estado'),
        ),
    ]
