# Generated by Django 4.2.1 on 2023-07-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0014_alter_mensajecontacto_estado_alter_playlist_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='artista',
            field=models.CharField(max_length=250, verbose_name='Artista'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Titulo'),
        ),
    ]
