# Generated by Django 4.1.5 on 2023-08-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfirmaAsistente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_contacto',
            name='id_intolerancias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ConfirmaAsistente.d_intolerancias', verbose_name='Intolerancias'),
        ),
    ]
